blank_issues_enabled: false
contact_links:
  - name: ðŸ’¬ Discusiones del Proyecto
    url: https://github.com/RodrigoMijangos/recolecta_web/discussions
    about: Para preguntas generales, ideas o discusiones sobre el proyecto
  - name: ðŸ“– DocumentaciÃ³n
    url: https://github.com/RodrigoMijangos/recolecta_web/blob/main/README.md
    about: Consulta la documentaciÃ³n completa del proyecto
